name: ecommerce_shop
description: Modern e-commerce mobile app with payment integration, real-time inventory, and AI-powered recommendations.

publish_to: 'none'

version: 3.2.0+25

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.7.0
  
  # Navigation
  go_router: ^12.1.3
  auto_route: ^7.8.4
  
  # Data & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  
  # Authentication
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_firestore: ^4.13.6
  google_sign_in: ^6.2.1
  facebook_auth: ^6.0.4
  
  # Payment Integration
  stripe_payment: ^1.1.4
  paypal_payment: ^1.0.6
  razorpay_flutter: ^1.3.0
  flutter_paystack: ^1.0.7
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  firebase_messaging: ^14.7.10
  awesome_notifications: ^0.8.2
  
  # Camera & Media
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  video_player: ^2.8.1
  photo_view: ^0.14.0
  
  # Location & Maps
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  package_info_plus: ^4.2.0
  
  # Charts & Visualization
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^23.2.7
  
  # AI & ML
  tflite_flutter: ^0.10.4
  mlkit: ^0.15.0
  
  # QR Code & Barcode
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  
  # Social Features
  share_plus: ^7.2.1
  flutter_share: ^2.0.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  isar_generator: ^3.1.0+1
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/products/
    - assets/categories/
    - assets/banners/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
